services: 
  db:
    image: postgres:14-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: sharjbook
      POSTGRES_USER: sharjuser
      POSTGRES_PASSWORD: sharjpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: .
    container_name: backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3 --log-level info
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SECRET_KEY=test
      - DEBUG=True
      - DB_NAME=sharjbook
      - DB_USER=sharjuser
      - DB_PASSWORD=sharjpass
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  
  



  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"


  worker:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379



volumes:
  postgres_data:
