# Generated by Django 5.2 on 2025-11-26 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_buildingfund"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="debt",
            name="resident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="debts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر بدهکار",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="resident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="پرداخت\u200cکننده",
            ),
        ),
    ]
