# Generated by Django 5.2 on 2025-12-26 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_alter_debt_resident_alter_payment_resident"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="reference_code",
        ),
        migrations.AddField(
            model_name="payment",
            name="debt",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="finance.debt",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "در انتظار"),
                    ("SUCCESS", "موفق"),
                    ("FAILED", "ناموفق"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="finance.transaction",
                verbose_name="تراکنش مربوطه",
            ),
        ),
        migrations.CreateModel(
            name="ZarinpalTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authority", models.CharField(max_length=255, unique=True)),
                ("ref_id", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zarinpal",
                        to="finance.payment",
                    ),
                ),
            ],
        ),
    ]
