# Generated by Django 5.2 on 2026-02-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_alter_transaction_options_remove_debt_resident_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.TextField(blank=True, default=1, verbose_name="توضیحات"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="zarinpaltransaction",
            name="ref_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
