# Generated by Django 5.2 on 2025-11-12 20:01

import buildings.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField(verbose_name='آدرس ساختمان')),
                ('name', models.CharField(max_length=300, verbose_name='نام ساختمان')),
                ('image', models.ImageField(blank=True, null=True, upload_to=buildings.models.Building.building_image_upload_path, verbose_name='عکس از ساختمان ')),
                ('building_type', models.CharField(choices=[('Building', 'ساختمان'), ('Block', 'بلوک'), ('Complex', 'مجتمع'), ('Tower', 'برج'), ('Town', 'شهرک')], max_length=20, verbose_name='نوع ساختمان')),
                ('use_type', models.CharField(choices=[('Residential', 'مسکونی'), ('Office', 'اداری'), ('Commercial', 'تجاری'), ('Medical', 'پزشکی'), ('Educational', 'آموزشی'), ('Villa', 'ویلا')], max_length=20, verbose_name='کاربری ساختمان')),
                ('units', models.PositiveIntegerField(verbose_name='تعداد واحدها')),
                ('shaba_number', models.CharField(max_length=26, validators=[django.core.validators.RegexValidator(message='شماره شبا باید با IR شروع شده و 24 رقم داشته باشد. مثال: IR123456789012345678901234', regex='^IR\\d{24}$')], verbose_name='شماره شبا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال')),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'MANAGER'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_buildings', to=settings.AUTH_USER_MODEL, verbose_name='مدیر ساختمان')),
            ],
            options={
                'verbose_name': 'ساختمان',
                'verbose_name_plural': 'ساختمان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuildingResident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اضافه شدن')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تأیید مدیر')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_residents', to=settings.AUTH_USER_MODEL, verbose_name='افزوده شده توسط')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_residents', to='buildings.building', verbose_name='ساختمان')),
                ('resident', models.ForeignKey(limit_choices_to={'role': 'RESIDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='residences', to=settings.AUTH_USER_MODEL, verbose_name='ساکن')),
            ],
            options={
                'verbose_name': 'ساکن ساختمان',
                'verbose_name_plural': 'ساکنین ساختمان',
                'unique_together': {('building', 'resident')},
            },
        ),
        migrations.AddField(
            model_name='building',
            name='residents',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'RESIDENT'}, related_name='residential_buildings', through='buildings.BuildingResident', through_fields=('building', 'resident'), to=settings.AUTH_USER_MODEL, verbose_name='ساکنین'),
        ),
    ]
