# Generated by Django 5.2 on 2025-11-26 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0002_building_monthly_charge_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="residents",
            field=models.ManyToManyField(
                blank=True,
                related_name="residential_buildings",
                through="buildings.BuildingResident",
                through_fields=("building", "resident"),
                to=settings.AUTH_USER_MODEL,
                verbose_name="ساکنین",
            ),
        ),
    ]
