# Generated by Django 5.2 on 2025-12-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_buildingresident_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingresident',
            name='unit',
            field=models.PositiveIntegerField(max_length=10, verbose_name='واحد'),
        ),
    ]
