# Generated by Django 5.2 on 2025-12-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0006_alter_buildingresident_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingresident',
            name='unit',
            field=models.PositiveIntegerField(verbose_name='واحد'),
        ),
    ]
