# Generated by Django 5.2 on 2025-11-24 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="نام"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="نام خانوادگی"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=13,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="شماره تماس باید با +98 شروع شود و 10 رقم بعد از آن بیاید. مثال: +989123456789",
                        regex="^\\+98\\d{10}$",
                    )
                ],
                verbose_name="شماره تماس",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("MANAGER", "مدیر ساختمان"), ("RESIDENT", "ساکن")],
                default="MANAGER",
                max_length=20,
                verbose_name="نقش کاربر",
            ),
        ),
    ]
