# Generated by Django 5.2 on 2026-01-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='discription',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='توضیحات کاربر'),
        ),
    ]
