# Generated by Django 5.2 on 2026-02-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="discription",
            field=models.TextField(
                blank=True, default=1, max_length=300, verbose_name="توضیحات کاربر"
            ),
            preserve_default=False,
        ),
    ]
