# Generated by Django 5.2 on 2026-06-30 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_profile_discription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, unique=True, verbose_name="ایمیل"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="شماره تماس باید با +98 شروع شود و 10 رقم بعد از آن بیاید. مثال: +989123456789",
                        regex="^\\+98\\d{10}$",
                    )
                ],
                verbose_name="شماره تماس",
            ),
        ),
    ]
