# Generated by Django 5.2 on 2026-08-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_profile_email_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("MANAGER", "مدیر ساختمان"), ("RESIDENT", "ساکن")],
                default="",
                max_length=20,
                verbose_name="نقش کاربر",
            ),
        ),
    ]
