name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Django check
        run: |
          python core/manage.py check

  deploy:
    needs: check
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:

          script: |
            cd ${{ secrets.PROJECT_PATH }}

            docker-compose -f docker-compose-stage.yml down

            git pull origin main

            docker-compose -f docker-compose-stage.yml restart